// Code generated by "stringer -linecomment -type=brokerErr"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[errSubscriberIndexed-1]
}

const _brokerErr_name = "subscriber has indexed in SuberscriberIndex"

var _brokerErr_index = [...]uint8{0, 43}

func (i brokerErr) String() string {
	i -= 1
	if i < 0 || i >= brokerErr(len(_brokerErr_index)-1) {
		return "brokerErr(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _brokerErr_name[_brokerErr_index[i]:_brokerErr_index[i+1]]
}
